apiVersion: v1
kind: Pod
metadata:
   name: app1
   labels:
    env: test
spec:
   containers:
    - image: krons/app
      name: app1
      ports:
        - containerPort: 8000
      resources:
        requests:
           cpu: "10m"
           memory: "1024Mi"
        limits:
           cpu: "20m"
           memory: "4024Mi"
      restartPolicy: Always
          
